### ISSUE TITLE
Cannot Read property toString of null with minimal example

### ISSUE THREAD

**Issue by MatteoRagni** [pkra/mathjax-node-svg2png#6]
with this code:

```js
var mj = require("mathjax-node-svg2png");

mj.config({
  MathJax: { }
});

mj.typeset({
  math: 'E = mc^2',
  format: 'TeX',
  png: true
}, function(d) {  });
```

I receive the following error
```
TypeError: Cannot read property 'toString' of null
```
with the following stack:
```
at processResult (.../node_modules/svg2png/lib/svg2png.js:58:33)
at Function.module.exports.sync (.../node_modules/svg2png/lib/svg2png.js:25:12)
at convert (.../node_modules/mathjax-node-svg2png/lib/main.js:61:32)
at .../node_modules/mathjax-node-svg2png/lib/main.js:51:23
at ReturnResult (.../node_modules/mathjax-node/lib/main.js:778:3)
at Function.execute (.../node_modules/mathjax/unpacked/MathJax.js:243:26)
at cb (.../node_modules/mathjax/unpacked/MathJax.js:225:59)
at Object.Process (.../node_modules/mathjax/unpacked/MathJax.js:495:38)
at Object.Push (.../node_modules/mathjax/unpacked/MathJax.js:485:49)
at Object.Queue (.../node_modules/mathjax/unpacked/MathJax.js:2057:28)
```

Am I doing something wrong?

**Comment by pkra** [comment]
Thanks for the report. 

I'm unable to reproduce this problem. Could you share the version of each dependency as well as node itself?

**Comment by MatteoRagni** [comment]
I've tested it on another system and it works. I'm closing it for now...

**Comment by pkra** [comment]
Ok. I'd still be happy to get more details on the issue.

**Comment by MatteoRagni** [comment]
As soon as I will have that laptop in my hand again, I will test it for more detail. But I'm starting to suspect a corrupted installation...

**Comment by pkra** [comment]
That's never happened to me :wink:
